### ISSUE TITLE
Input RDF file format

### ISSUE THREAD

**Issue by wiqijan2002** [aschaetzle/S2RDF#2]
on Web site http://dbis.informatik.uni-freiburg.de/forschung/projekte/DiPoS/S2RDF.html  it is mentioned to input RDF file as nt. but on a GitHub page it is written to input file as .tsv. Will you plz specify which input RDF format should be used

**Comment by TheTinkerJ** [comment]
According to the source code in S2RDF_DataSetCreator/src/main/scala/DataSetGenerator.scala 

```scala
  /**
   * Generate TripleTable and save it to Parquet file in HDFS.
   * The table has to be cached, since it is used for generation of VP and ExtVP
   */
  private def createTT() = {      
    val df = _sc.textFile(Settings.inputRDFSet)
                         .map(_.split("\t"))
                         .map( p => Triple(p(0), p(1), p(2)))
                         .toDF()
```

the input RDF file is .tsv 

but in my view .nt is also readable because when parsing `s p o .` the first three elements will be used to construct the dataset, there is no problem with it
